import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { Metadata } from "next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AI Analizer",
  description: "Generated by create next app",
};

/**
 * Root layout component that applies global font CSS variables and provides the page container.
 *
 * Renders an HTML root element with a body element that includes configured font class names and antialiasing, then renders `children` followed by the app `Toaster`.
 *
 * @param children - The React nodes to render inside the layout body
 * @returns The application's root HTML structure containing the body with font classes and the Toaster
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}